name: ci
on: [push, pull_request]

env:
  # Use file-based MLflow so no server is needed
  MLFLOW_TRACKING_URI: file:mlruns

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install pipx && pipx install poetry

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - run: poetry install --no-interaction --no-root

      
      - name: Lint
        run: |
          poetry run python -m pip install ruff black
          poetry run ruff check .
          poetry run black --check .

      # Smoke test Streamlit app only (no dvc pull needed)
      - name: Streamlit smoke
        run: |
          nohup poetry run streamlit run src/app.py --server.headless true --server.port 8501 >/dev/null 2>&1 &
          sleep 10
          curl -f http://localhost:8501/
